### ISSUE TITLE
monitoring docker: no such container

### ISSUE THREAD

**Issue by abu-adm** [flo-at/minmon#141]
Hello, would it be possible to consider non existent container as a standard alarm condition (i.e. not running)?

afaik container states can be:
1. running/null
2. running/healthy
3. running/unhealthy
4. exited
5. non existent

Right now, 1-4 are monitored as expected (1-2 OK, 3-4 ALARM), but condition 5 just trigger monitoring error. However I still consider container, which I explicitly state in minmon config to be monitored, even non existent, as not running, and hence deserving alarm (yes, I use stateless containers with bind mounts, so when they are stopped, they are removed hence docker does not know about their state). I've checked the code, and the docker library returns error and reply with "Docker error: Docker responded with status code 404: No such container: mycontainer", unfortunatelly I can't code in rust, but would it be possible to detect this special condition (for example by output regexp) and make it a standard alarm instead an error, equal to condition 4?

**Comment by flo-at** [comment]
You're right, it shouldn't be considered a check error when a container does not exist. We know it's not running if this happens. I changed the code to reflect this and I'll make a new release tomorrow. Thanks for pointing this out!

Please don't forget to close the ticket once you've tested the fix.

**Comment by abu-adm** [comment]
Now it works as expected, thanks for the fix.

Btw. great project, I use it on my personal servers, where it do exactly what I need (I have long experience with many other monitoring solutions from my job).
