### ISSUE TITLE
Rethink just a single toml file

### ISSUE THREAD

**Issue by hammerandtongs** [flo-at/minmon#17]
The reasoning behind many/most monitoring solutions having "fancy" config directory structure is that its a requirement.

People need to be able to put monitoring in place for something they bring up with automated tools.

Editing a toml file is a nonstarter (and no concating it in doesn't work either).

I would recommend going through the mental or actual code exercise of parsing some example nagios configs. Steelman why things are the way they are and you'll find it illuminating (I did it a decade ago for an in house golang monitoring server). 

https://en.wikipedia.org/wiki/Straw_man#Steelmanning

**Comment by flo-at** [comment]
I'll take a look at it, thanks! It would be possible to either pass a single file or a directory and treat both cases differently. I'm not sure if automated deployments are a good use case for this tool though. It's targeting single-machine setups, not a client-server model which is typically used to gather the data from multiple machines.
