### ISSUE TITLE
Point in time in addition to interval for report trigger

### ISSUE THREAD

**Issue by othiman** [flo-at/minmon#180]
Hi,

I would love to have the possibility to have a point in time configurable instead of an interval. This would, e.g., enable that alive reports from different servers arrive at the same time so that it is easier to see if a report is missing.

A crontab-like definition style would be an option to define it.

Best regards,
Thomas

**Comment by flo-at** [comment]
I'd prefer to use it like this too know that you talked about it :-)
This will be implemented in the upcoming v0.8.0 release.

Example for every Mondat at 10 (UTC):
```toml
[report]
cron = "0 0 10 * * Mon"
```
