### ISSUE TITLE
Testing an alert 

### ISSUE THREAD

**Issue by cfredericksen** [flo-at/minmon#41]
I set the filesystem threshold to 85. My mount was 86 to see if my alert would work. Nothing happened and nothing in the logs. Shouldn't the log show an alert? I will post my config if necessary.

**Comment by flo-at** [comment]
Hi, can you please try to set the log level to debug and see what it says? It should print all measured values on each interval. Also, the implementation measures the free space available to the user (there should be a note in the Readme about it), depending on your setup that's less than the total available space, maybe that's the reason. How (which tool) do you measure the usage manually?

If that doesn't help, could you please send your config file and the relevant lines from the output of `df -h`?

Cheers

**Comment by flo-at** [comment]
@cfredericksen any update on this?

**Comment by cfredericksen** [comment]
> @cfredericksen any update on this?

Not yet. Will test it this week. Thanks.

**Comment by flo-at** [comment]
Hi @cfredericksen, do you have any news on this? If not I would close this ticket for now and you can re-open a new one once there is more information (e.g. log output or config) available. Have a good day!
