### ISSUE TITLE
Fail to install on debian

### ISSUE THREAD

**Issue by daufinsyd** [flo-at/minmon#91]
Hello

I wanted tor try minmon but I can't get to install it on Debian 11.
```
# cargo install --all-features minmon
    Updating crates.io index
  Downloaded minmon v0.4.1
error: failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/minmon-0.4.1/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`
root@pve2:~# cargo install --all-features minmon
    Updating crates.io index
error: failed to download `minmon v0.4.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/minmon-0.4.1/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`
```

The Cargo.toml looks like
```
...
[profile.release]
lto = true
panic = "abort"
strip = true

[dependencies.async-trait]
...
```

I'm using cargo 1.46.0

Am I doing something wrong ?

**Comment by flo-at** [comment]
Hi, thanks for the report.
I guess that using booleans for the strip config was added in a more recent version of cargo.

Can you try to replace the line `strip = true` in Cargo.toml with `strip = "symbols"` and see if it works?

Here's the documentation of that option: https://doc.rust-lang.org/cargo/reference/profiles.html

I'll check if it makes sense to replace this in the repository later today.

**Comment by daufinsyd** [comment]
Thanks for the solution !
It works that way (actually I got another error 'this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.') but I'll update to Debian 12 in the upcoming days/weeks and give another try.

Indeed it would have been cool if cargo first checked the edition

**Comment by flo-at** [comment]
You're welcome! I'll close the issue then.

I'm not sure about Debian but some distros (and Rust itself iirc) recommend using rustup to install the Rust toolchain instead of the distro packages. This way you don't need to update the whole distro in your case.
